name: Windows - Litemanager
on:
 workflow_dispatch:

 
jobs:
  build:
        name: Start Building...
        runs-on: windows-latest
        
        steps:
        - name: Downloading & instaling Essentials
        run: |
        Invoke-WebRequest -Un
"https://gitlab.com/chamod12/Im_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile
"Downloads_bat"
      cmd /c Downloads.bat
      
      - name: Connect to LiteManager
      run: cmd/c show.bat
      
      - name: Time Counter
      run: cmd /c loop.bat
