name Windows-Lilemanager
on:
workflow _dispalch:
jobs
build
name: Start Building
runs-on: windows-latest
sleps
name. Downloading & instaling Essentials
nn|
Invoke-WebRequest Ur
"https://igtlab.com/chamod12/Im_win-10_github_rdp/-/raw/main/Downioads.bar -OuFilc
"Downloads_bat"
cmd /c Downloads.bat
name. Connect to LieManager
run cmd/c show bat
name: "Time Counter
run: cmd /c loopibat
